### PR TITLE
#118 - JAR doesn't always include both slashes

### PR DESCRIPTION
**Pull request by max-norris**
Fixes the issue where a JAR file is found but the protocol doesn't include both slashes

### CODE REVIEW

**Comment by max-norris** [comment]
fix for issue #118

**Comment by tcurrie** [comment]
@max-norris when you get a minute, can you review the tests I suggested?  Oshoukry is a stickler for testing.  And though the previous implementation has gaps in the testing of the jar handling, covering the use cases affected by the change will make it simpler to incorporate.

**Comment by max-norris** [comment]
Will do, I'll get the tests added tonight.

**Comment by max-norris** [comment]
@tcurrie Added a test with an example string that I was getting in my project.

**Pull request closed without merging**
